### ISSUE TITLE
Create API routes

### ISSUE THREAD

**Issue by Jay1194** [Jay1194/Note-Taker#3]
**description**

- `Get /api/notes` should read the `db.json` file and return all saved notes as JSON.

- `POST /api/notes` should receive a new note to save on the request body, add it to the `db.file` file, and then return the new note to the client.

- Look through npm packages for a way to give each note a unique `id` when saved.

**Comment by ApurvaPradhan** [comment]
I am new to open source, but I am eager to contribute. Could you please assign me a task?

**Comment by Jay1194** [comment]
Hey, I apologize for the confusion. I'm currently working on an individual project for a class, but it would be great if we could connect, follow each other, and potentially collaborate in the future. I'm curious to learn more about your skill set. What are your strengths and areas of expertise?
